/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package connect;

import java.awt.Color;
import java.awt.Font;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;
import net.proteanit.sql.DbUtils;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author IMRD
 */
public class student extends javax.swing.JFrame {

 
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    
    
    public student() {
        initComponents();
        conn=Connect.connection();
        jTable1();
    }
    /**
     * Creates new form student
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void jTable1() {
        JTableHeader t=jTable1.getTableHeader();
        t.setForeground(Color.BLUE);
        t.setFont(new Font("Arial",Font.BOLD,19));
        try {
            String sql = "SELECT `STUDENT_NO`, `STUDENT_Name`,`STUDENT_DOB`,`STUDENT_DOJ` FROM `student`";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studno = new javax.swing.JLabel();
        studname = new javax.swing.JLabel();
        studdob = new javax.swing.JLabel();
        studdoj = new javax.swing.JLabel();
        student_name = new javax.swing.JTextField();
        student_no = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        search_no = new javax.swing.JTextField();
        insert = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        student_dob = new javax.swing.JTextField();
        student_doj = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studno.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        studno.setText("Student no");
        getContentPane().add(studno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, 40));

        studname.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        studname.setText("student Name");
        getContentPane().add(studname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 160, 40));

        studdob.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        studdob.setText("Student DOB");
        getContentPane().add(studdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 140, 40));

        studdoj.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        studdoj.setText("Student DOJ Date");
        getContentPane().add(studdoj, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 180, 40));

        student_name.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        getContentPane().add(student_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 230, -1));

        student_no.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        getContentPane().add(student_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 230, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "student no", "student name", "DOB", "DOJ"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 420, 370));

        search_no.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        getContentPane().add(search_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 474, 250, -1));

        insert.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        insert.setText("INSERT");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });
        getContentPane().add(insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 140, 40));

        update.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        delete.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, -1));

        student_dob.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        getContentPane().add(student_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 230, 40));

        student_doj.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        getContentPane().add(student_doj, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 230, 40));

        search.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        search.setText("search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connect/Student-feedback-on-blog.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        // TODO add your handling code here:
        if(student_no.getText().equals(""))
        JOptionPane.showMessageDialog(this,"Please enter Student Id");
        else if(student_name.getText().equals(""))
        JOptionPane.showMessageDialog(this,"Please enter Student name");
        else if(student_dob.getText().equals(""))
        JOptionPane.showMessageDialog(this,"Please enter Student DOB");
        else if(student_doj.getText().equals(""))
        JOptionPane.showMessageDialog(this,"Please enter Student DOJ date");
        else
        try{
            String sql = "INSERT INTO `student`(`STUDENT_NO`, `STUDENT_NAME`,`STUDENT_DOB`,`STUDENT_DOJ`) VALUES (?,?,?,?)";
            pst=conn.prepareStatement(sql);
            pst.setString(1, student_no.getText());
            pst.setString(2, student_name.getText());
            pst.setString(3, student_dob.getText());
            pst.setString(4, student_doj.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Successfully Student Added...!!");
            pst.close();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "student Denied...!!");
        }
        jTable1();
    }//GEN-LAST:event_insertActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        Update();
        jTable1();
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        Delete();
        jTable1();
    }//GEN-LAST:event_deleteActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int selectedRowIndex = jTable1.getSelectedRow();
        student_no.setText(model.getValueAt(selectedRowIndex, 0).toString());
        student_name.setText(model.getValueAt(selectedRowIndex, 1).toString());
        student_dob.setText(model.getValueAt(selectedRowIndex, 2).toString());
        student_doj.setText(model.getValueAt(selectedRowIndex, 3).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        Search();
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JButton insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton search;
    private javax.swing.JTextField search_no;
    private javax.swing.JLabel studdob;
    private javax.swing.JLabel studdoj;
    private javax.swing.JTextField student_dob;
    private javax.swing.JTextField student_doj;
    private javax.swing.JTextField student_name;
    private javax.swing.JTextField student_no;
    private javax.swing.JLabel studname;
    private javax.swing.JLabel studno;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

   

    private void Update() {
        try {
            pst = conn.prepareStatement("UPDATE `student` SET STUDENT_DOJ=? WHERE STUDENT_NO=?");
            pst.setString(1, student_doj.getText());
            pst.setString(2, student_no.getText());
            pst.execute();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
         JOptionPane.showMessageDialog(null,"its update....!!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Update Denied....!!");
        }
        jTable1();
    }
   

    private void Delete() {
String sql= "DELETE FROM `student` WHERE STUDENT_NO=?";
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, student_no.getText());
            pst.execute();
            
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
   }

    private void Search() {
         try {
            String sql = "SELECT `STUDENT_NO`, `STUDENT_NAME`,`STUDENT_DOB`,`STUDENT_DOJ` FROM `student` WHERE STUDENT_NO=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1,search_no.getText());
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            JOptionPane.showMessageDialog(null,"It's Search...!!");
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null,"Search Denied....!!");
        }
    }

}


    

